import React, { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { api } from "../api/client.js";

export default function ProcessDetail() {
  const { id } = useParams();
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    api.getProcess(id).then(setData).catch((e) => setError(e.message));
  }, [id]);

  if (error) return <p className="error">Error: {error}</p>;
  if (!data) return <p className="muted">Loading...</p>;

  return (
    <div>
      <Link to="/processes" className="back-link">&larr; All Processes</Link>
      <h1>{data.process_name}</h1>
      <p className="muted">{data.category}</p>

      <section className="panel">
        <h2>Scoring</h2>
        <div className="stats-row">
          <StatCard label="Automation Potential" value={data.automation_potential} />
          <StatCard label="Automation Score" value={data.automation_score?.toFixed(1)} />
          <StatCard label="Priority Score" value={data.priority_score?.toFixed(1)} />
          <StatCard label="Confidence" value={data.confidence?.toFixed(2)} />
        </div>
        <p className="muted small">
          Scores are computed deterministically from activity signals, evidence coverage,
          and benefit/risk weighting — not generated by the language model.
        </p>
      </section>

      <section className="panel">
        <h2>Business Purpose</h2>
        <p>{data.business_purpose}</p>
      </section>

      <section className="panel">
        <h2>Key Activities</h2>
        <ul>{(data.key_activities || []).map((a, i) => <li key={i}>{a}</li>)}</ul>
      </section>

      <div className="two-col">
        <section className="panel">
          <h2>Current Challenges</h2>
          <p>{data.current_challenges}</p>
        </section>
        <section className="panel">
          <h2>AI Opportunity</h2>
          <p>{data.ai_opportunity}</p>
        </section>
      </div>

      <div className="two-col">
        <section className="panel">
          <h2>Human Involvement</h2>
          <p>{data.human_involvement}</p>
        </section>
        <section className="panel">
          <h2>Technologies</h2>
          <ul>{(data.technologies || []).map((t, i) => <li key={i}>{t}</li>)}</ul>
        </section>
      </div>

      <div className="two-col">
        <section className="panel">
          <h2>Business Benefit</h2>
          <p>{data.business_benefit}</p>
        </section>
        <section className="panel">
          <h2>Risks</h2>
          <p>{data.risks}</p>
        </section>
      </div>

      <section className="panel">
        <h2>Evidence ({data.evidence.length})</h2>
        {data.evidence.length === 0 && (
          <p className="muted">
            No research evidence cleared the relevance threshold for this process.
            The analysis above is based on the process description and general
            reasoning only — treat conclusions with lower confidence.
          </p>
        )}
        {data.evidence.map((e, i) => (
          <div key={i} className="evidence-card">
            <div className="evidence-title">
              <a href={e.url} target="_blank" rel="noreferrer">{e.title}</a>
              <span className="muted small"> — relevance {e.relevance_score.toFixed(2)}</span>
            </div>
            <p className="small">{e.snippet}</p>
          </div>
        ))}
      </section>

      <p className="muted small">Model used: {data.model_used}</p>
    </div>
  );
}

function StatCard({ label, value }) {
  return (
    <div className="stat-card">
      <div className="stat-value">{value ?? "—"}</div>
      <div className="stat-label">{label}</div>
    </div>
  );
}
